# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': '\u4f59\u989d',
                'verbose_name_plural': '\u4f59\u989d',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name=b'\xe4\xbb\xb7\xe5\x80\xbc')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name=b'\xe4\xbd\x99\xe9\x87\x8f')),
            ],
            options={
                'verbose_name': '\u6cb9\u5361',
                'verbose_name_plural': '\u6cb9\u5361',
            },
        ),
        migrations.CreateModel(
            name='CoalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': '\u7164\u7c7b\u578b',
                'verbose_name_plural': '\u7164\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7164\u77ff',
                'verbose_name_plural': '\u7164\u77ff',
            },
        ),
        migrations.CreateModel(
            name='OutRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(blank=True, max_length=10)),
                ('driver_name', models.CharField(blank=True, max_length=10)),
                ('contact_info', models.CharField(blank=True, max_length=20)),
                ('unit', models.FloatField()),
                ('amount', models.FloatField()),
                ('setoff_time', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.CharField(blank=True, max_length=10)),
                ('payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('out_unit', models.FloatField(verbose_name=b'\xe5\x87\xba\xe8\xb4\xa7\xe5\x8d\x95\xe4\xbb\xb7')),
                ('amount_in', models.FloatField(default=0.0)),
                ('amount_out', models.FloatField(default=0.0)),
                ('amount_balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u78c5\u623f',
                'verbose_name_plural': '\u78c5\u623f',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField(verbose_name=b'\xe8\xbf\x90\xe8\xb4\xb9\xe5\x8d\x95\xe4\xbb\xb7')),
                ('coal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.CoalType', verbose_name=b'\xe7\x85\xa4\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Mine', verbose_name=b'\xe5\x87\xba\xe5\x8f\x91\xe7\x85\xa4\xe7\x9f\xbf')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Scale', verbose_name=b'\xe5\x88\xb0\xe8\xbe\xbe\xe7\xa3\x85\xe6\x88\xbf')),
            ],
            options={
                'verbose_name': '\u8fd0\u8d39',
                'verbose_name_plural': '\u8fd0\u8d39',
            },
        ),
        migrations.CreateModel(
            name='TransRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=10)),
                ('contact_info', models.CharField(max_length=20)),
                ('setoff_time', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.CharField(max_length=10, null=True, unique=True)),
                ('setoff_amount', models.FloatField(null=True)),
                ('arrive_amount', models.FloatField(null=True)),
                ('arrive_time', models.DateTimeField(null=True)),
                ('unit', models.FloatField(null=True)),
                ('cash', models.FloatField(null=True)),
                ('card_payed', models.BooleanField(default=False)),
                ('cash_payed', models.BooleanField(default=False)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Card')),
                ('coal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.CoalType')),
                ('mine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Mine')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Scale')),
            ],
            options={
                'permissions': (('mine', 'mine'), ('scale', 'scale'), ('account', 'account')),
            },
        ),
        migrations.AddField(
            model_name='outrec',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Scale'),
        ),
    ]
