# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='coal_type',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.AddField(
            model_name='userscaleinfo',
            name='scale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.Scale', verbose_name=b'\xe7\xa3\x85\xe6\x88\xbf'),
        ),
    ]
