# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transrec',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
