# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_scale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transrec',
            name='arrive_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transrec',
            name='setoff_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
