# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_auto_20151228_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscaleinfo',
            options={'verbose_name': '\u7528\u6237\u6240\u5c5e\u78c5\u623f', 'verbose_name_plural': '\u7528\u6237\u6240\u5c5e\u78c5\u623f'},
        ),
        migrations.AddField(
            model_name='transrec',
            name='opaccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opaccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transrec',
            name='opscale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opscale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transrec',
            name='mine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Mine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transrec',
            name='qrcode',
            field=models.CharField(default=11, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transrec',
            name='scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Scale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userscaleinfo',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Scale', verbose_name=b'\xe7\xa3\x85\xe6\x88\xbf'),
        ),
        migrations.AlterField(
            model_name='userscaleinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
    ]
