# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0003_auto_20151210_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Mine')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Scale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermine',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='usermine',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMine',
        ),
    ]
