# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20151213_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transrec',
            name='arrive_time',
            field=models.DateTimeField(null=True),
        ),
    ]
