# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20151211_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Mine'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Scale'),
        ),
    ]
