# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_scale_out_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='amount_balance',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='amount_in',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='amount_out',
        ),
    ]
