# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20151211_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='transrec',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Scale'),
        ),
    ]
